export const data = [
    {
      id: "1",
      name: "Laptop",
      description: "High-performance laptop for professionals",
      color: 'White and black',
      price: 1200.00,
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-01-men-category-04.jpg',
      imageAlt: 'Front of zip tote bag with white canvas, black canvas straps and handle, and black zipper pulls.',
      category: "Electronics",
      inStock: true,
    },
    {
      id: "2",
      name: "Smartphone",
      description: "Latest model with high-resolution camera",
      color: 'White and black',
      price: 900.00,
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-01-men-category-03.jpg',
      imageAlt: 'Grey 6-panel baseball hat with black brim, black mountain graphic on front, and light heather gray body',
      category: "Electronics",
      inStock: true,
    },
    {
        "id": "3",
        "name": "Coffee Maker",
        "description": "Brews coffee in minutes",
        color: 'White and black',
        "price": 80.00,
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-category-01.jpg',
        imageAlt: 'Models sitting back to back, wearing Basic Tee in black and bone.',
        "category": "Home Appliances",
        inStock: true,
    },
    {
        "id": "4",
        "name": "Running Shoes",
        "description": "Comfortable and durable",
        color: 'White and black',
        "price": 120.00,
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-category-03.jpg',
        imageAlt: 'Model wearing minimalist watch with black wristband and white watch face.',
        "category": "Footwear",
        inStock: true,
    },
    {
        "id": "5",
        "name": "Desk Chair",
        "description": "Ergonomic and stylish",
        color: 'White and black',
        "price": 220.00,
        "imageSrc": 'https://tailwindui.com/img/ecommerce-images/product-page-03-related-product-01.jpg',
        imageAlt: 'Front of zip tote bag with white canvas, black canvas straps and handle, and black zipper pulls.',
        "category": "Furniture",
        inStock: true,
    },
    {
      id: "6",
      name: "Laptop",
      description: "High-performance laptop for professionals",
      color: 'White and black',
      price: 1200.00,
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-01-men-category-04.jpg',
      imageAlt: 'Front of zip tote bag with white canvas, black canvas straps and handle, and black zipper pulls.',
      category: "Electronics",
      inStock: true,

    },
    {
      id: "7",
      name: "Smartphone",
      description: "Latest model with high-resolution camera",
      color: 'White and black',
      price: 900.00,
      imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-01-men-category-03.jpg',
      imageAlt: 'Grey 6-panel baseball hat with black brim, black mountain graphic on front, and light heather gray body',
      category: "Electronics",
      inStock: true,
    },
    {
        "id": "8",
        "name": "Coffee Maker",
        "description": "Brews coffee in minutes",
        color: 'White and black',
        "price": 80.00,
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-category-01.jpg',
        imageAlt: 'Models sitting back to back, wearing Basic Tee in black and bone.',
        "category": "Home Appliances",
        inStock: true,
    },
    {
        "id": "9",
        "name": "Running Shoes",
        "description": "Comfortable and durable",
        color: 'White and black',
        "price": 120.00,
        imageSrc: 'https://tailwindui.com/img/ecommerce-images/mega-menu-category-03.jpg',
        imageAlt: 'Model wearing minimalist watch with black wristband and white watch face.',
        "category": "Footwear",
        inStock: true,

    },
    {
        "id": "10",
        "name": "Desk Chair",
        "description": "Ergonomic and stylish",
        color: 'White and black',
        "price": 220.00,
        "imageSrc": 'https://tailwindui.com/img/ecommerce-images/product-page-03-related-product-01.jpg',
        imageAlt: 'Front of zip tote bag with white canvas, black canvas straps and handle, and black zipper pulls.',
        "category": "Furniture",
        inStock: true,
    }

  ];


